### ISSUE TITLE
how to provide public_url in tileserver docker-compose.yml?

### ISSUE THREAD

**Issue by nishanthdn96** [maptiler/tileserver-gl#470]
**docker-compose.yml**
```
  wms:
    container_name: tos_tileserver
    image: maptiler/tileserver-gl
    command: '--public_url /tileserver'
    volumes:
      - ./uploads/tile-server:/data
    privileged: true
    restart: on-failure
    networks:
      - app-network

```
**nginx.conf**
```
      location /tileserver {
                proxy_pass http://wms;
	        index index.html;
                proxy_redirect  off;
                rewrite ^/tileserver/(.*) $1 break;

      }
```
I'm trying to run tileserver using docker-compose file. I want to load tileserver on subpath(http:domain.com/tileserver). It is running on the root path but not on subpath. 
Please guide to load tileserver on the subpath using public_url which can be passed as an option.
