### ISSUE TITLE
Error: listen EACCES: permission denied 0.0.0.0:80

### ISSUE THREAD

**Issue by aconital** [maptiler/tileserver-gl#503]
I have a simple ubuntu server and when I run the following command:
`docker run --rm -it -v $(pwd):/data -p 8080:80 maptiler/tileserver-gl` I get this error:

`Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1263:19)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/app/node_modules/express/lib/application.js:618:24)
    at start (/app/src/server.js:450:22)
    at module.exports.opts (/app/src/server.js:469:19)
    at startServer (/app/src/main.js:80:29)
    at fs.stat (/app/src/main.js:211:12)
    at FSReqWrap.oncomplete (fs.js:154:5)
Emitted 'error' event at:
    at emitErrorNT (net.js:1307:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

I tried running it with sudo as well but same thing

**Comment by eitProp** [comment]
I tried running the same command with v3.1.0 and the server wouldn't start up either. However, I seem to be getting no explicit permission error li

**Comment by eitProp** [comment]
I got this error as well while trying to run v3.1.1. I also tried running the same command with v3.1.0, and even though it didn’t give any explicit error messages during start up the viewer wouldn’t even open up on the designated port. The same command was working properly with V3.0.0 though.

**Comment by hassan-essabir** [comment]
Try to use `-u 0` in order to run it as root : 
`docker run --rm -u 0 -it -v $(pwd):/data -p 8080:80 maptiler/tileserver-gl`
This works perfectly

**Comment by aconital** [comment]
Do we need to run it as root though? Previous versions where working fine.

**Comment by hassan-essabir** [comment]
It runs as root inside the container only.
They are trying to bind to the port 80 as a non root user which is never gonna work unless the user is a sudoer.
For me, it's a regression that needs to be fixed by maptiler.
The solution I suggested is only a work around.

**Comment by StephanZaat** [comment]
I would suggest running the container on another port instead of the default 80.
I use this in my Kubernetes manifest: 
```   
- name: tileserver
        image: maptiler/tileserver-gl
        args: ["-p", "8080", "--verbose", "-c", "/var/config/<my_config>.json"]
```

In Compose:
```  
tileserver:
    image: maptiler/tileserver-gl
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/data:/data"
      - "$PWD/tileserver/config:/var/config:ro"
      - "$PWD/tileserver/static:/var/static:ro"
    command: -p 8080 --verbose -c /var/config/<my_config>.json
```

In Docker Run:
`docker run --rm -it -v $(pwd):/data -p 8080:8080 maptiler/tileserver-gl -p 8080 --verbose`

Running as root is not necessary then.
